In [2]:
'''
1.  What is NumPy and what are its main advantages over regular Python lists? 
   -  Coding Challenge:  Create a NumPy array from a list of numbers and perform basic 
   arithmetic operations (addition, multiplication) on the array.

Ans. NumPy stands for numerical python
it is faster to access anf manipulate than list and stores only one siingle type of data
'''
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
arr=arr1+arr2
print(arr1+arr2)
print("\n")
print(arr1-arr2)
print("\n")
print(arr1*arr2)
print("\n")
print(arr1/arr2)

[ 5  7  9 11]


[-3 -3 -3 -3]


[ 4 10 18 28]


[0.25       0.4        0.5        0.57142857]


In [3]:
'''
2.  How can you create different types of arrays in NumPy, such as arrays filled with zeros, ones, or random values? 
   -  Coding Challenge:  Write a Python script that creates a 3x3 array of zeros, a 3x3 array of ones, 
   and a 3x3 array of random integers between 1 and 10.

'''
print(np.zeros(9).reshape(-1,3))
print(np.ones(9).reshape(-1,3))
print(np.random.randint(1,10,9).reshape(-1,3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4 9 3]
 [9 5 6]
 [9 7 2]]


In [4]:
'''
3.  Explain how array indexing and slicing work in NumPy. How does it differ from standard Python list indexing? 
   -  Coding Challenge:  Create a 2D NumPy array and use slicing to extract a subarray from it. 
   For example, extract a 2x2 subarray from a 4x4 array.

'''
arr3=np.random.randint(20,60,16).reshape(-1,4)
print(arr3)
print("\n")
print(arr3[0:2,2:4])

[[56 41 32 27]
 [21 45 23 27]
 [33 22 22 39]
 [57 27 43 25]]


[[32 27]
 [23 27]]


In [10]:
'''
4.  What are some common functions in NumPy for performing statistical operations, such as mean, median,
and standard deviation? 
   -  Coding Challenge:  Write a Python script that computes the mean, median, and standard deviation
     of a NumPy array containing 100 random values.

'''
arr4=np.random.randint(1,101,100)
print(arr4.mean())
np.sort(arr4)
median=(arr4[50]+arr4[51])/2
print(median)
print(arr4.std())


53.1
67.0
28.46032325888095


In [24]:
'''
5.  How can you perform element-wise operations and matrix operations using NumPy? Provide examples of both. 
   -  Coding Challenge:  Create two 2D NumPy arrays and perform element-wise addition, subtraction, and matrix
     multiplication.

'''
arr5=np.random.randint(1,20,8).reshape(-1,2)
arr6=np.random.randint(1,20,8).reshape(-1,2)
print(arr5*arr6)
print(arr5-arr6)
arr7=np.random.randint(1,20,8).reshape(-1,4)
print(arr7@arr6)

[[ 45 255]
 [ 78 342]
 [ 90  44]
 [ 18  70]]
[[-12   2]
 [  7  -1]
 [  1   7]
 [  3  -3]]
[[351 393]
 [204 300]]


In [45]:
'''
6.  What are broadcasting and how does it work in NumPy? How can you use it to perform operations on arrays 
of different shapes? 
   -  Coding Challenge:  Write a Python script that demonstrates broadcasting by adding a 1D array to each 
   row of a 2D array.

'''
arr8=np.random.randint(1,10,3)
arr9=np.random.randint(1,10,9).reshape(-1,3)
m=arr9.shape[0]
sum=np.array()
for i in range(m):
    sum.append(arr8+arr9[i])
np.array(sum)
print(sum)

TypeError: array() missing required argument 'object' (pos 0)

In [58]:
'''
7.  How do you handle missing or NaN values in NumPy arrays? What functions or methods can be used for this purpose? 
   -  Coding Challenge:  Create a NumPy array with some NaN values and use NumPy functions to replace NaNs 
   with the mean of the array.

'''
a=np.array([1,4,3,np.nan,5,3,np.nan])
y=np.nanmean(a)
is_nan=np.isnan(a)
a_replaced=np.nan_to_num(a,nan=y)
a_replaced

array([1. , 4. , 3. , 3.2, 5. , 3. , 3.2])

In [64]:
'''
8.  Explain the purpose and usage of NumPy's `reshape()` and `flatten()` methods. 
How can you change the shape of an array? 
   -  Coding Challenge:  Write a Python script that creates a 1D array with 12 elements, 
   reshapes it into a 3x4 array, and then flattens it back into a 1D array.

'''
arr10=np.array([1,2,3,6,5,2,3,1,5,4,8,5]).reshape(3,4)
arr10.reshape(-1)

array([1, 2, 3, 6, 5, 2, 3, 1, 5, 4, 8, 5])

In [65]:
'''
9.  What is the role of `numpy.linalg` for linear algebra operations? 
How can you use it to perform operations like matrix inversion or eigenvalue computation? 
   -  Coding Challenge:  Create a 2x2 matrix and use `numpy.linalg.inv()` to compute its 
   inverse. Also, compute the eigenvalues and eigenvectors of the matrix.

'''


'\n9.  What is the role of `numpy.linalg` for linear algebra operations? \nHow can you use it to perform operations like matrix inversion or eigenvalue computation? \n   -  Coding Challenge:  Create a 2x2 matrix and use `numpy.linalg.inv()` to compute its \n   inverse. Also, compute the eigenvalues and eigenvectors of the matrix.\n\n'

In [70]:
'''
10.  How can you save and load NumPy arrays to and from files? What formats are supported? 
    -  Coding Challenge:  Write a Python script that saves a NumPy array to a file using 
    `numpy.save()` and then loads it back using `numpy.load()`.

'''
n=np.random.randint(1,10,12)
np.save("numpy_file",n,arr10)
np.load("numpy_file.npy")

array([3, 4, 6, 6, 9, 8, 9, 5, 5, 4, 3, 6])