In [1]:
import numpy as np
np.__version__

#1D,2D,3D,4D...

'1.24.2'

In [2]:
lst=[1,2,3,4,5]
ar1=np.array(lst)
print(ar1)
ar1
print(type(ar1))


p=(1,2,3,4,5)
ar3=np.array(p)
print(ar3)


s="samika"
ar2=np.array(s)
print(ar2)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
samika


In [3]:
print(np.arange(1,20,1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
print(np.linspace(1,20,6))

[ 1.   4.8  8.6 12.4 16.2 20. ]


In [5]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [6]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [7]:
a=np.zeros((4,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
y=a.reshape(2,10)
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr7=np.random.random(25)
arr7

array([0.98817236, 0.37620024, 0.78727812, 0.43853097, 0.6569261 ,
       0.64439339, 0.1139339 , 0.73467441, 0.45264028, 0.44493385,
       0.85502674, 0.9226376 , 0.20346525, 0.61825514, 0.49482637,
       0.66624913, 0.82430957, 0.7949419 , 0.76880369, 0.8690855 ,
       0.2739958 , 0.50508123, 0.76211522, 0.03322657, 0.55227334])

In [21]:
ar4=np.arange(50,110)
arn=ar4.reshape(2,30)

print(arn)
print(arn.shape)

print(arn.dtype)

print(arn.ndim)

ar5=np.random.random(25)

[[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
   68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99 100 101 102 103 104 105 106 107 108 109]]
(2, 30)
int32
2


In [22]:
ar4.ravel()

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109])

In [23]:
ar4.flatten()

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109])

In [34]:
u=ar4.reshape(20,3)
print(u)

[[ 50  51  52]
 [ 53  54  55]
 [ 56  57  58]
 [ 59  60  61]
 [ 62  63  64]
 [ 65  66  67]
 [ 68  69  70]
 [ 71  72  73]
 [ 74  75  76]
 [ 77  78  79]
 [ 80  81  82]
 [ 83  84  85]
 [ 86  87  88]
 [ 89  90  91]
 [ 92  93  94]
 [ 95  96  97]
 [ 98  99 100]
 [101 102 103]
 [104 105 106]
 [107 108 109]]


In [31]:
x=u.shape
print(x)
ar6=u.T.shape
print(ar6)

(20, 3)
(3, 20)


In [33]:
#indexing and slicing
#1D array: same as normal
ar8=np.array([1,5,6,8,9,4,5])
print(ar8[2:5])
ar8[3]=99
print(ar8)

[6 8 9]
[ 1  5  6 99  9  4  5]


In [42]:
#2D array
print(u[1:3,1:2])

[[54]
 [57]]


In [ ]:
print(u[:,:2])


[[ 50  51]
 [ 53  54]
 [ 56  57]
 [ 59  60]
 [ 62  63]
 [ 65  66]
 [ 68  69]
 [ 71  72]
 [ 74  75]
 [ 77  78]
 [ 80  81]
 [ 83  84]
 [ 86  87]
 [ 89  90]
 [ 92  93]
 [ 95  96]
 [ 98  99]
 [101 102]
 [104 105]
 [107 108]]


array([[50]])

In [56]:
print(u[0:1,0:1][0][0])
print(type(u[0:1,0:1][0][0]))

50
<class 'numpy.int32'>


In [62]:
#print(u[::-1])
print(u[:,::-1])


[[ 52  51  50]
 [ 55  54  53]
 [ 58  57  56]
 [ 61  60  59]
 [ 64  63  62]
 [ 67  66  65]
 [ 70  69  68]
 [ 73  72  71]
 [ 76  75  74]
 [ 79  78  77]
 [ 82  81  80]
 [ 85  84  83]
 [ 88  87  86]
 [ 91  90  89]
 [ 94  93  92]
 [ 97  96  95]
 [100  99  98]
 [103 102 101]
 [106 105 104]
 [109 108 107]]


In [69]:
ar9=np.arange(32).reshape(2,4,4)
#print(ar9)
print(np.sum(ar9,axis=0))

[[16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]


In [74]:
x=np.array([1,2,3,4,5,6,98,5,4,58,9,6,8,9,6,52,2,6,85,2,6,5,4,8,9,7,6])
x.shape=((3,3,3))
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [98  5  4]]

 [[58  9  6]
  [ 8  9  6]
  [52  2  6]]

 [[85  2  6]
  [ 5  4  8]
  [ 9  7  6]]]


In [78]:
#slicing in 3D array
#suntax:
#[table start:table end:table skip,row start:row end:row skip,col start:col end:col skip]
o=x[1:2,1:2,0:1]
print(o[0][0][0])

8


In [99]:
j=[1,2,3,5,6,4,8,6]
print(np.max(j))
print(np.min(j))
print(np.std(j))
print(np.sum(j))
print(np.mean(j))
print(np.median(j))
print(np.sort(j))
print("\n")
print(np.sort(j)[::-1])


8
1
2.1758618981911515
35
4.375
4.5
[1 2 3 4 5 6 6 8]


[8 6 6 5 4 3 2 1]


In [104]:
ar10=np.array([1,2,3,6,5])
ar11=np.array([9,6,2,3,5])
print(ar10*ar11)
print(ar10*6)

[ 9 12  6 18 25]
[ 6 12 18 36 30]
