In [1]:
# csv
# series--1D labelled array capable of holding only one datatype
#dataframe--is a 2D labelled data data stucture
#basically a table with rows and columns
import pandas as pd


In [2]:
import numpy as np

In [3]:
df=pd.read_csv(r"C:\Users\Gargi\OneDrive\Desktop\data science\Library\Data\Used_Bikes.csv")
#agar same folder me data file ho toh exam naam dedo bss varna path
#df=pd.read_csv("Used_Bikes.csv")
print(df)
type(df)

                                  bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power        

pandas.core.frame.DataFrame

In [4]:
dt={
    "name":["gargi","vidhi","khushish"],
    "score":[1,2,3],
    "age":[55,85,99]
}
dt

{'name': ['gargi', 'vidhi', 'khushish'],
 'score': [1, 2, 3],
 'age': [55, 85, 99]}

In [5]:
df1=pd.DataFrame(dt)
df1

name  score  age
0     gargi      1   55
1     vidhi      2   85
2  khushish      3   99

In [6]:
arr=np.arange(1,61).reshape(10,6)
print(arr)
pd.DataFrame(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30
5  31  32  33  34  35  36
6  37  38  39  40  41  42
7  43  44  45  46  47  48
8  49  50  51  52  53  54
9  55  56  57  58  59  60

In [7]:
df2=pd.DataFrame(arr,columns=["a","b","c","d","e","f"])
df2

a   b   c   d   e   f
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30
5  31  32  33  34  35  36
6  37  38  39  40  41  42
7  43  44  45  46  47  48
8  49  50  51  52  53  54
9  55  56  57  58  59  60

In [8]:
df2.head()

a   b   c   d   e   f
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30

In [9]:
df2.tail(3)

a   b   c   d   e   f
7  43  44  45  46  47  48
8  49  50  51  52  53  54
9  55  56  57  58  59  60

In [10]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [11]:
type(df["bike_name"])#1D labelled array
df["bike_name"]

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...                 
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: object

In [12]:
df.dtypes

bike_name      object
price         float64
city           object
kms_driven    float64
owner          object
age           float64
power         float64
brand          object
dtype: object

In [13]:
#fetching multiple columns
df[["bike_name","city"]]

bike_name       city
0        TVS Star City Plus Dual Tone 110cc  Ahmedabad
1               Royal Enfield Classic 350cc      Delhi
2                      Triumph Daytona 675R      Delhi
3                      TVS Apache RTR 180cc  Bangalore
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore
...                                     ...        ...
32643                Hero Passion Pro 100cc      Delhi
32644                  TVS Apache RTR 180cc     Karnal
32645              Bajaj Avenger Street 220      Delhi
32646             Hero Super Splendor 125cc     Jaipur
32647                    Bajaj Pulsar 150cc       Pune

[32648 rows x 2 columns]

In [14]:
#for rows
df[0:3]

bike_name     price       city  kms_driven  \
0  TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1         Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                Triumph Daytona 675R  600000.0      Delhi       110.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph

In [15]:
#for columns
#iloc--integer location
#loc--label location
print(df.iloc[0:3,0:3])
#iloc--issey hum continous columns ko hi select kr sakte h
df.loc[[1,3],["bike_name","age"]]

                            bike_name     price       city
0  TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad
1         Royal Enfield Classic 350cc  119900.0      Delhi
2                Triumph Daytona 675R  600000.0      Delhi


bike_name  age
1  Royal Enfield Classic 350cc  4.0
3         TVS Apache RTR 180cc  4.0

In [16]:
np.array(df)

array([['TVS Star City Plus Dual Tone 110cc', 35000.0, 'Ahmedabad', ...,
        3.0, 110.0, 'TVS'],
       ['Royal Enfield Classic 350cc', 119900.0, 'Delhi', ..., 4.0,
        350.0, 'Royal Enfield'],
       ['Triumph Daytona 675R', 600000.0, 'Delhi', ..., 8.0, 675.0,
        'Triumph'],
       ...,
       ['Bajaj Avenger Street 220', 60000.0, 'Delhi', ..., 6.0, 220.0,
        'Bajaj'],
       ['Hero Super Splendor 125cc', 15600.0, 'Jaipur', ..., 16.0, 125.0,
        'Hero'],
       ['Bajaj Pulsar 150cc', 22000.0, 'Pune', ..., 13.0, 150.0, 'Bajaj']],
      dtype=object)

In [17]:
df.max()
#agar sab pe lagaya toh hr ek coulumn ki jo max value hogi vo yeh return kr dega

bike_name     Yezdi Classic 250cc
price                   1900000.0
city                     Zirakpur
kms_driven               750000.0
owner                 Third Owner
age                          63.0
power                      1800.0
brand                       Yezdi
dtype: object

In [24]:
df["price"].max()
df["price"].min()
df["price"].std()
df["price"].var()
df["price"].median()
df["price"].mode()
df["price"].cumsum()
print(df["price"].cumprod())


0        3.500000e+04
1        4.196500e+09
2        2.517900e+15
3        1.636635e+20
4        1.309308e+25
             ...     
32643             inf
32644             inf
32645             inf
32646             inf
32647             inf
Name: price, Length: 32648, dtype: float64


c:\Users\Gargi\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)


In [19]:
#print(df["city"].unique())
df["city"].nunique()#count of unique values
print(df["city"].value_counts())

Delhi            7318
Bangalore        2723
Mumbai           2591
Hyderabad        2160
Pune             1724
                 ... 
Surendranagar       1
Khandela            1
Mohammadabad        1
Shimla              1
Sidhi               1
Name: city, Length: 443, dtype: int64


In [20]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='object')

In [21]:
#filtering data based on condition
df["city"]=="Delhi"

0        False
1         True
2         True
3        False
4        False
         ...  
32643     True
32644    False
32645     True
32646    False
32647    False
Name: city, Length: 32648, dtype: bool

In [22]:
if(df["city"]=="Delhi"):
    df["brand"]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
df[df["city"]=="Delhi"]

bike_name     price   city  kms_driven  \
1              Royal Enfield Classic 350cc  119900.0  Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0  Delhi       110.0   
5                         Yamaha FZs 150cc   53499.0  Delhi     25000.0   
6            Honda CB Hornet 160R  ABS DLX   85000.0  Delhi      8200.0   
7      Hero Splendor Plus Self Alloy 100cc   45000.0  Delhi     12645.0   
...                                    ...       ...    ...         ...   
32639          Royal Enfield Classic 350cc   95500.0  Delhi     18000.0   
32640               Hero Passion Pro 100cc   32000.0  Delhi     12000.0   
32641                  Bajaj Avenger 220cc   41000.0  Delhi     20245.0   
32643               Hero Passion Pro 100cc   39000.0  Delhi     22000.0   
32645             Bajaj Avenger Street 220   60000.0  Delhi     20373.0   

              owner   age  power          brand  
1       First Owner   4.0  350.0  Royal Enfield  
2       First Owner   8.0  675.0        Triumph  
5       First Owner   6.0  150.0         Yamaha  
6       First Owner   3.0  160.0          Honda  
7       First Owner   3.0  100.0           Hero  
...             ...   ...    ...            ...  
32639   First Owner   8.0  350.0  Royal Enfield  
32640   First Owner   6.0  100.0           Hero  
32641  Second Owner  11.0  220.0          Bajaj  
32643   First Owner   4.0  100.0           Hero  
32645   First Owner   6.0  220.0          Bajaj  

[7318 rows x 8 columns]

In [ ]:
delhi=df[df["city"]=="Delhi"]
print(delhi)
delhi["owner"].value_counts()
#naya dataframe delhi me stored h
#owner==fourth owner 4th hand
#print(delhi[delhi["owner"]=="Fourth Owner Or More"]["bike_name"])

                                 bike_name     price   city  kms_driven  \
1              Royal Enfield Classic 350cc  119900.0  Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0  Delhi       110.0   
5                         Yamaha FZs 150cc   53499.0  Delhi     25000.0   
6            Honda CB Hornet 160R  ABS DLX   85000.0  Delhi      8200.0   
7      Hero Splendor Plus Self Alloy 100cc   45000.0  Delhi     12645.0   
...                                    ...       ...    ...         ...   
32639          Royal Enfield Classic 350cc   95500.0  Delhi     18000.0   
32640               Hero Passion Pro 100cc   32000.0  Delhi     12000.0   
32641                  Bajaj Avenger 220cc   41000.0  Delhi     20245.0   
32643               Hero Passion Pro 100cc   39000.0  Delhi     22000.0   
32645             Bajaj Avenger Street 220   60000.0  Delhi     20373.0   

              owner   age  power          brand  
1       First Owner   4.0  350.0  Royal Enfield  

First Owner             6516
Second Owner             787
Third Owner               13
Fourth Owner Or More       2
Name: owner, dtype: int64

In [ ]:
delhi[delhi["kms_driven"]<65000][["bike_name","kms_driven"]]

bike_name  kms_driven
1              Royal Enfield Classic 350cc     11000.0
2                     Triumph Daytona 675R       110.0
5                         Yamaha FZs 150cc     25000.0
6            Honda CB Hornet 160R  ABS DLX      8200.0
7      Hero Splendor Plus Self Alloy 100cc     12645.0
...                                    ...         ...
32639          Royal Enfield Classic 350cc     18000.0
32640               Hero Passion Pro 100cc     12000.0
32641                  Bajaj Avenger 220cc     20245.0
32643               Hero Passion Pro 100cc     22000.0
32645             Bajaj Avenger Street 220     20373.0

[6654 rows x 2 columns]

In [ ]:

delhi[delhi["kms_driven"]<65000][["bike_name","kms_driven"]].head()

bike_name  kms_driven
1          Royal Enfield Classic 350cc     11000.0
2                 Triumph Daytona 675R       110.0
5                     Yamaha FZs 150cc     25000.0
6        Honda CB Hornet 160R  ABS DLX      8200.0
7  Hero Splendor Plus Self Alloy 100cc     12645.0

In [ ]:
#using multiple comditions
#problemstatement--brand=tvs,age less than 3 ,price less than 50000
tvs=df[(df["brand"]=="TVS")&(df["age"]<3)&(df["price"]<50000)]
tvs

bike_name    price       city  kms_driven        owner  age  \
7055  TVS Sport 100cc  46000.0  Faridabad      6222.0  First Owner  2.0   

      power brand  
7055  100.0   TVS

In [ ]:
#checks duplicate record in a dataset
df.duplicated().sum()

25324

In [ ]:
df.drop_duplicates()
#bina duplicates ka dataset ht jate h
#used for data cleaning
#prrr yeh save nhi hota h yaani 
print(df.duplicated().sum())
df.drop_duplicates()
print(df.duplicated().sum())

#permanent save krne k liye:
df.drop_duplicates(inplace=True)
print(df.duplicated().sum())

25324
25324
0


In [ ]:
#null value in dataset
df.isnull().sum()
df.dropna(inplace=True)
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [ ]:
#kisi bhi format k andar save karane k liye
df.to_excel("excel_data.xlsx", index=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   bike_name   7324 non-null   object 
 1   price       7324 non-null   float64
 2   city        7324 non-null   object 
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   object 
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   object 
dtypes: float64(4), object(4)
memory usage: 515.0+ KB


In [ ]:
dt2={
    "a":[1,2,3,4],
    "b":[5,np.nan,7,np.nan],
    "c":[np.nan,9,np.nan,11]
}
dt3=pd.DataFrame(dt2)
print(dt3.isnull())
print(dt3.isnull().sum())
print(dt3.isnull().sum().sum())

       a      b      c
0  False  False   True
1  False   True  False
2  False  False   True
3  False   True  False
a    0
b    2
c    2
dtype: int64
4


In [ ]:
dt3.dropna()
#puri row ko hata dia jisme ek bhi bhi null value h
dt3.dropna(axis=1)
#0--row
#1--column


a
0  1
1  2
2  3
3  4

In [ ]:
print(dt3.isnull())
#null ki jagha constant value daal dena
dt3.fillna(0)

       a      b      c
0  False  False   True
1  False   True  False
2  False  False   True
3  False   True  False


a    b     c
0  1  5.0   0.0
1  2  0.0   9.0
2  3  7.0   0.0
3  4  0.0  11.0

In [ ]:
#df.loc[0:10,["price"]]=np.nan

In [ ]:
df.head()

bike_name  price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc    NaN  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc    NaN      Delhi     11000.0   
2                  Triumph Daytona 675R    NaN      Delhi       110.0   
3                  TVS Apache RTR 180cc    NaN  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition    NaN  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [ ]:
df.fillna(df["price"].mean())

bike_name          price       city  \
0       TVS Star City Plus Dual Tone 110cc   84821.726378  Ahmedabad   
1              Royal Enfield Classic 350cc   84821.726378      Delhi   
2                     Triumph Daytona 675R   84821.726378      Delhi   
3                     TVS Apache RTR 180cc   84821.726378  Bangalore   
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition   84821.726378  Bangalore   
...                                    ...            ...        ...   
9362             Hero Hunk Rear Disc 150cc   25000.000000      Delhi   
9369                   Bajaj Avenger 220cc   35000.000000  Bangalore   
9370        Harley-Davidson Street 750 ABS  450000.000000    Jodhpur   
9371                 Bajaj Dominar 400 ABS  139000.000000  Hyderabad   
9372              Bajaj Avenger Street 220   80000.000000  Hyderabad   

      kms_driven        owner  age  power            brand  
0        17654.0  First Owner  3.0  110.0              TVS  
1        11000.0  First Owner  4.0  350.0    Royal Enfield  
2          110.0  First Owner  8.0  675.0          Triumph  
3        16329.0  First Owner  4.0  180.0              TVS  
4        10000.0  First Owner  3.0  150.0           Yamaha  
...          ...          ...  ...    ...              ...  
9362     48587.0  First Owner  8.0  150.0             Hero  
9369     60000.0  First Owner  9.0  220.0            Bajaj  
9370      3430.0  First Owner  4.0  750.0  Harley-Davidson  
9371     21300.0  First Owner  4.0  400.0            Bajaj  
9372      7127.0  First Owner  5.0  220.0            Bajaj  

[7324 rows x 8 columns]

In [ ]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
df["price"]+5000
#ismen inplace nhi hota toh save karane k liye
df["price"]=df["price"]+5000
df["inc_price"]=df["price"]+5000
df["add_age_price"]=df["age"]+df["price"]
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   75000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  159900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  640000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc  105000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition  120000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   79000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   70000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220  100000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   55600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   62000.0       Pune     60857.0   

             owner   age  power          brand  inc_price  add_age_price  
0      First Owner   3.0  110.0            TVS    80000.0        75003.0  
1      First Owner   4.0  350.0  Royal Enfield   164900.0       159904.0  
2      First Owner   8.0  675.0        Triumph   645000.0       640008.0  
3      First Owner   4.0  180.0            TVS   110000.0       105004.0  
4      First Owner   3.0  150.0         Yamaha   125000.0       120003.0  
...            ...   ...    ...            ...        ...            ...  
32643  First Owner   4.0  100.0           Hero    84000.0        79004.0  
32644  First Owner   9.0  180.0            TVS    75000.0        70009.0  
32645  First Owner   6.0  220.0          Bajaj   105000.0       100006.0  
32646  First Owner  16.0  125.0           Hero    60600.0        55616.0  
32647  First Owner  13.0  150.0          Bajaj    67000.0        62013.0  

[32648 rows x 10 columns]

In [ ]:
df.drop("add_age_price",axis=1)

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   75000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  159900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  640000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc  105000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition  120000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   79000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   70000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220  100000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   55600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   62000.0       Pune     60857.0   

             owner   age  power          brand  inc_price  
0      First Owner   3.0  110.0            TVS    80000.0  
1      First Owner   4.0  350.0  Royal Enfield   164900.0  
2      First Owner   8.0  675.0        Triumph   645000.0  
3      First Owner   4.0  180.0            TVS   110000.0  
4      First Owner   3.0  150.0         Yamaha   125000.0  
...            ...   ...    ...            ...        ...  
32643  First Owner   4.0  100.0           Hero    84000.0  
32644  First Owner   9.0  180.0            TVS    75000.0  
32645  First Owner   6.0  220.0          Bajaj   105000.0  
32646  First Owner  16.0  125.0           Hero    60600.0  
32647  First Owner  13.0  150.0          Bajaj    67000.0  

[32648 rows x 9 columns]

In [ ]:
df.drop(["add_age_price","power"],axis=1)

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   75000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  159900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  640000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc  105000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition  120000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   79000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   70000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220  100000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   55600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   62000.0       Pune     60857.0   

             owner   age          brand  inc_price  
0      First Owner   3.0            TVS    80000.0  
1      First Owner   4.0  Royal Enfield   164900.0  
2      First Owner   8.0        Triumph   645000.0  
3      First Owner   4.0            TVS   110000.0  
4      First Owner   3.0         Yamaha   125000.0  
...            ...   ...            ...        ...  
32643  First Owner   4.0           Hero    84000.0  
32644  First Owner   9.0            TVS    75000.0  
32645  First Owner   6.0          Bajaj   105000.0  
32646  First Owner  16.0           Hero    60600.0  
32647  First Owner  13.0          Bajaj    67000.0  

[32648 rows x 8 columns]

In [ ]:
df.rename(columns={"kms_driven":"km_driven"},inplace=True)
df

bike_name     price       city  km_driven  \
0        TVS Star City Plus Dual Tone 110cc   75000.0  Ahmedabad    17654.0   
1               Royal Enfield Classic 350cc  159900.0      Delhi    11000.0   
2                      Triumph Daytona 675R  640000.0      Delhi      110.0   
3                      TVS Apache RTR 180cc  105000.0  Bangalore    16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition  120000.0  Bangalore    10000.0   
...                                     ...       ...        ...        ...   
32643                Hero Passion Pro 100cc   79000.0      Delhi    22000.0   
32644                  TVS Apache RTR 180cc   70000.0     Karnal     6639.0   
32645              Bajaj Avenger Street 220  100000.0      Delhi    20373.0   
32646             Hero Super Splendor 125cc   55600.0     Jaipur    84186.0   
32647                    Bajaj Pulsar 150cc   62000.0       Pune    60857.0   

             owner   age  power          brand  inc_price  add_age_price  
0      First Owner   3.0  110.0            TVS    80000.0        75003.0  
1      First Owner   4.0  350.0  Royal Enfield   164900.0       159904.0  
2      First Owner   8.0  675.0        Triumph   645000.0       640008.0  
3      First Owner   4.0  180.0            TVS   110000.0       105004.0  
4      First Owner   3.0  150.0         Yamaha   125000.0       120003.0  
...            ...   ...    ...            ...        ...            ...  
32643  First Owner   4.0  100.0           Hero    84000.0        79004.0  
32644  First Owner   9.0  180.0            TVS    75000.0        70009.0  
32645  First Owner   6.0  220.0          Bajaj   105000.0       100006.0  
32646  First Owner  16.0  125.0           Hero    60600.0        55616.0  
32647  First Owner  13.0  150.0          Bajaj    67000.0        62013.0  

[32648 rows x 10 columns]

In [ ]:
df.loc[[0,3],["price"]]+1

price
0   75001.0
3  105001.0

In [ ]:
#group by
owner_group=df.groupby("owner")
owner_group

In [ ]:
owner_group.get_group("First Owner")

bike_name     price       city  km_driven  \
0        TVS Star City Plus Dual Tone 110cc   75000.0  Ahmedabad    17654.0   
1               Royal Enfield Classic 350cc  159900.0      Delhi    11000.0   
2                      Triumph Daytona 675R  640000.0      Delhi      110.0   
3                      TVS Apache RTR 180cc  105000.0  Bangalore    16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition  120000.0  Bangalore    10000.0   
...                                     ...       ...        ...        ...   
32643                Hero Passion Pro 100cc   79000.0      Delhi    22000.0   
32644                  TVS Apache RTR 180cc   70000.0     Karnal     6639.0   
32645              Bajaj Avenger Street 220  100000.0      Delhi    20373.0   
32646             Hero Super Splendor 125cc   55600.0     Jaipur    84186.0   
32647                    Bajaj Pulsar 150cc   62000.0       Pune    60857.0   

             owner   age  power          brand  inc_price  add_age_price  
0      First Owner   3.0  110.0            TVS    80000.0        75003.0  
1      First Owner   4.0  350.0  Royal Enfield   164900.0       159904.0  
2      First Owner   8.0  675.0        Triumph   645000.0       640008.0  
3      First Owner   4.0  180.0            TVS   110000.0       105004.0  
4      First Owner   3.0  150.0         Yamaha   125000.0       120003.0  
...            ...   ...    ...            ...        ...            ...  
32643  First Owner   4.0  100.0           Hero    84000.0        79004.0  
32644  First Owner   9.0  180.0            TVS    75000.0        70009.0  
32645  First Owner   6.0  220.0          Bajaj   105000.0       100006.0  
32646  First Owner  16.0  125.0           Hero    60600.0        55616.0  
32647  First Owner  13.0  150.0          Bajaj    67000.0        62013.0  

[29964 rows x 10 columns]

In [ ]:
#aggregate
owner_group["age"].agg(min_age="min",Max_age="max",Mean_age="mean")

min_age  Max_age   Mean_age
owner                                            
First Owner               1.0     43.0   7.684855
Fourth Owner Or More      4.0     37.0  15.250000
Second Owner              2.0     63.0  12.129095
Third Owner               4.0     43.0  11.175926

In [ ]:
brand_group=df.groupby("brand")
brand_group

In [ ]:
brand_group.get_group("TVS")

bike_name     price       city  km_driven  \
0      TVS Star City Plus Dual Tone 110cc   75000.0  Ahmedabad    17654.0   
3                    TVS Apache RTR 180cc  105000.0  Bangalore    16329.0   
52                   TVS Apache RTR 160cc  100000.0     Mumbai    30000.0   
114            TVS Apache RTR 160 4V Disc  109900.0      Delhi     8700.0   
130                TVS Phoenix Disc 125cc   61500.0    Barasat    10500.0   
...                                   ...       ...        ...        ...   
32549                TVS Apache RTR 180cc   70000.0     Karnal     6639.0   
32568                TVS Apache RTR 180cc   70000.0     Karnal     6639.0   
32587                TVS Apache RTR 180cc   70000.0     Karnal     6639.0   
32606                TVS Apache RTR 180cc   70000.0     Karnal     6639.0   
32644                TVS Apache RTR 180cc   70000.0     Karnal     6639.0   

             owner  age  power brand  inc_price  add_age_price  
0      First Owner  3.0  110.0   TVS    80000.0        75003.0  
3      First Owner  4.0  180.0   TVS   110000.0       105004.0  
52     First Owner  5.0  160.0   TVS   105000.0       100005.0  
114    First Owner  3.0  160.0   TVS   114900.0       109903.0  
130    First Owner  5.0  125.0   TVS    66500.0        61505.0  
...            ...  ...    ...   ...        ...            ...  
32549  First Owner  9.0  180.0   TVS    75000.0        70009.0  
32568  First Owner  9.0  180.0   TVS    75000.0        70009.0  
32587  First Owner  9.0  180.0   TVS    75000.0        70009.0  
32606  First Owner  9.0  180.0   TVS    75000.0        70009.0  
32644  First Owner  9.0  180.0   TVS    75000.0        70009.0  

[1247 rows x 10 columns]

In [ ]:
#pip install matplotlib seaborn

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement matplotlib (from versions: none)
ERROR: No matching distribution found for matplotlib

[notice] A new release of pip available: 22.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
